# Generated by Django 3.2.8 on 2021-12-06 13:41

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Имя автора')),
                ('body', django_quill.fields.QuillField(verbose_name='Тело новости')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.TextField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Биография автора',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='Автор')),
                ('pdf_file', models.FileField(upload_to='media/')),
                ('cover', models.ImageField(upload_to='images/')),
                ('language', models.CharField(choices=[('KYRGYZ', 'КЫРГЫЗЧА'), ('RUSSIAN', 'НА РУССКОМ'), ('ENGLISH', 'IN ENGLISH'), ('TURKISH', 'TÜRKÇE')], default='RUSSIAN', max_length=20)),
                ('year', models.IntegerField()),
                ('discription', models.TextField(max_length=1000, verbose_name='Описание книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Заголовок новости')),
                ('img', models.ImageField(upload_to='images/')),
                ('body', django_quill.fields.QuillField(verbose_name='Тело новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('url_for', models.URLField(max_length=250, verbose_name='Ссылка на YouTube')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='blog.book')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='blog.category'),
        ),
    ]
